---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: cloud-iy
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 20
              "memory": 20
            targetThresholds:
              "memory": 50
              "cpu" : 50
            evictableNamespaces:
              exclude:
              - "cloud-iy"
              - "nfs-provisioner"
              - "local"
              - "default"
              - "kube-system"
              - "kube-node-lease"
              - "kube-public"
              - "cattle-system"
              - "cert-manager"
              - "fleet-local"
              - "cattle-global-nt"
              - "fleet-default"
              - "cattle-global-data"
              - "cattle-impersonation-system"
              - "cattle-fleet-system"
              - "cattle-fleet-clusters-system"
              - "cattle-provisioning-capi-system"
              - "cattle-fleet-local-system"
        - name: "LowNodeRealUtilization"
          args:
            thresholds:
              "cpu" : 20
              "memory": 20
            targetThresholds:
              "memory": 80
              "cpu" : 80
            evictableNamespaces:
              exclude:
              - "cloud-iy"
              - "nfs-provisioner"
              - "local"
              - "default"
              - "kube-system"
              - "kube-node-lease"
              - "kube-public"
              - "cattle-system"
              - "cert-manager"
              - "fleet-local"
              - "cattle-global-nt"
              - "fleet-default"
              - "cattle-global-data"
              - "cattle-impersonation-system"
              - "cattle-fleet-system"
              - "cattle-fleet-clusters-system"
              - "cattle-provisioning-capi-system"
              - "cattle-fleet-local-system"
        plugins:
          balance:
            enabled:
              - "LowNodeUtilization"
              - "LowNodeRealUtilization"
