---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: cloud-iy
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 20
              "memory": 20
            targetThresholds:
              "memory": 50
              "cpu" : 50
            evictableNamespaces:
              exclude:
              - "kube-system"
              - "cloud-iy"
              - "nfs-provisioner"
        - name: "LowNodeRealUtilization"
          args:
            thresholds:
              "cpu" : 20
              "memory": 20
            targetThresholds:
              "memory": 80
              "cpu" : 80
            evictableNamespaces:
              exclude:
              - "kube-system"
              - "cloud-iy"
              - "nfs-provisioner"
        plugins:
          balance:
            enabled:
              - "LowNodeUtilization"
              - "LowNodeRealUtilization"
