---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "LowNodeUtilization"
          args:
            thresholds:
              "cpu" : 20
              "memory": 20
            targetThresholds:
              "memory": 70
              "cpu" : 70
            evictableNamespaces:
              exclude:
              - "kube-system"
              - "cloud-iy"
        plugins:
          balance:
            enabled:
              - "LowNodeUtilization"