apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "lb-pool"
spec:
  cidrs:
  - cidr: "${HOST_IP}/32"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector: {}
  nodeSelector: {}
  interfaces:
  - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
