apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: cloud-iy
spec:
  repo: https://gitlab.com/api/v4/projects/54080196/packages/helm/cilium
  chart: cilium/cilium
  targetNamespace: cloud-iy
  dockerRegistrySecret: cloud-iy-credentials
  version: 1.16.0-dev-dev.270-HEAD-b82a6fd2ba
  set:
    kubeProxyReplacement=true
    k8sServiceHost=${HOST_IP}
    k8sServicePort=6443 
    bgp-annouce-lb-ips=true 
    bgpControlPlane.enabled=true 
    l2announcements.enabled=true 
    externalIPs.enabled=true 
    l2announcements.leaseDuration=3s 
    l2announcements.leaseRenewDeadline=1s 
    l2announcements.leaseRetryPeriod=200ms 
    imagePullSecrets[0].name=cloud-iy-credentials