apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool-metallb
  namespace: cloud-iy
spec:
  addresses:
    - ${HOST_IP}/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip-advertisment
  namespace: cloud-iy